# Generated by Django 4.1.3 on 2022-11-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RationalTourism', '0005_target_interactivescreen_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivescreen',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RationalTourism.target'),
        ),
    ]
